spring:
  application:
    name: inventory-service
  cloud:
    config:
      uri: http://config-service:${CONFIG_SERVICE_PORT:8086}
      enabled: true
  config:
    import: configserver:http://config-service:${CONFIG_SERVICE_PORT:8086}
