spring:
  GATEWAY_SERVICE_PORT: ${GATEWAY_SERVICE_PORT}
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://172.17.0.1:${USER_SERVICE_PORT:8082}/
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/users/(?<segment>.*), /$\{segment}

          - id: product-service
            uri: http://172.17.0.1:${PRODUCT_SERVICE_PORT:8083}/
            predicates:
              - Path=/products/**
            filters:
              - RewritePath=/products/(?<segment>.*), /$\{segment}

          - id: inventory-service
            uri: http://172.17.0.1:${INVENTORY_SERVICE_PORT:8084}/
            predicates:
              - Path=/inventory/**
            filters:
              - RewritePath=/inventory/(?<segment>.*), /$\{segment}

          - id: order-service
            uri: http://172.17.0.1:${ORDER_SERVICE_PORT:8085}/
            predicates:
              - Path=/orders/**
            filters:
              - RewritePath=/orders/(?<segment>.*), /$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8080/realms/microServsRealm

server:
  port: ${GATEWAY_SERVICE_PORT:8081}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true

