spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://user-service:${USER_SERVICE_PORT:8082}/
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/users/(?<segment>.*), /$\{segment}

          - id: product-service
            uri: http://product-service:${PRODUCT_SERVICE_PORT:8083}/
            predicates:
              - Path=/products/**
            filters:
              - RewritePath=/products/(?<segment>.*), /$\{segment}

          - id: inventory-service
            uri: http://inventory-service:${INVENTORY_SERVICE_PORT:8084}/
            predicates:
              - Path=/inventory/**
            filters:
              - RewritePath=/inventory/(?<segment>.*), /$\{segment}

          - id: order-service
            uri: http://order-service:${ORDER_SERVICE_PORT:8085}/
            predicates:
              - Path=/orders/**
            filters:
              - RewritePath=/orders/(?<segment>.*), /$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.201.46.94:8080/realms/microServsRealm
      client:
        provider:
          keycloak:
            issuer-uri: http://10.201.46.94:8080/realms/microServsRealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gatewayClient
            client-secret: Z2jPIyTUA9562YkipbTtabNu2gILR69C
            scope: openid

server:
  port: ${GATEWAY_SERVICE_PORT:8081}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true
