spring:
  application:
    name: inventory-service
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
      group-id:
        - all-products-group-1
        - sended-orders-group-1
  datasource:
    driver-class-name: org.postgresql.Driver
    password: bestuser
    username: bestuser
    url: jdbc:postgresql://postgres:5432/postgresDB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${INVENTORY_SERVICE_PORT:8084}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true
