spring:
  application:
    name: inventory-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id:
        - all-products-group-1
        - sended-orders-group-1
  datasource:
    driver-class-name: org.postgresql.Driver
    password: bestuser
    username: bestuser
    url: jdbc:postgresql://localhost:9090/postgresDB
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${INVENTORY_SERVICE_PORT:8084}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true
