spring:
  application:
    name: user-service
  kafka:
    producer:
      bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8080/realms/microServsRealm


server:
  port: ${USER_SERVICE_PORT:8082}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true