spring:
  application:
    name: user-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/microServsRealm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/microServsRealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: userClient
            client-secret: zVyu7pP1OEbYHw8Sz29K1zdPYYHFrPkh
            scope: openid

server:
  port: ${USER_SERVICE_PORT:8082}

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT:8181}/eureka/
  instance:
    prefer-ip-address: true