spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: bestuser
    username: bestuser
    url: jdbc:postgresql://localhost:9090/postgresDB
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    producer:
      bootstrap-servers: localhost:9092

server:
  port: 8085

eureka:
  client:
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: ${EUREKA_SERVICE_URI:http://localhost:8181/eureka/}
  instance:
    prefer-ip-address: true