spring:
  application:
    name: discovery-service
#  cloud:
#    config:
#      uri: http://localhost:${CONFIG_SERVICE_PORT:8086}
#      enabled: true
  config:
    import: configserver:http://localhost:${CONFIG_SERVICE_PORT:8086}/discovery-service